### ISSUE TITLE
增加协议

### ISSUE THREAD

**Issue by Unnamed-5** [yuying2012/WJDStudyLibrary#1]
你好
我需要在我们一个学术竞赛的工程的将会开源的软件中用到这个repo里的一些代码，但是理论上来讲你的repo没有加开源许可证，所以我是无权使用这些代码的，再加上比赛评定比较严格，严重可能会违法，所以请帮个忙加个开源协议，MIT，apache之类都行。谢谢了

**Comment by wjd-jax** [comment]
好

**Comment by wjd-jax** [comment]
已添加
